// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP56JAYYBifMKsNlSjEo_b0GKhD-708xM',
    appId: '1:928586580604:web:f176566c818a177a0cbff9',
    messagingSenderId: '928586580604',
    projectId: 'ssup-ca6a0',
    authDomain: 'ssup-ca6a0.firebaseapp.com',
    storageBucket: 'ssup-ca6a0.appspot.com',
    measurementId: 'G-PRT074MNVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtXy7R5FzlBEUpVIuydEj72_v-T_RH2mY',
    appId: '1:928586580604:android:549f7f85ac70ab550cbff9',
    messagingSenderId: '928586580604',
    projectId: 'ssup-ca6a0',
    storageBucket: 'ssup-ca6a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9WTHm8sl3_-aLHU61Rk2SXVdKW_VCGU4',
    appId: '1:928586580604:ios:a3d329f05a570b750cbff9',
    messagingSenderId: '928586580604',
    projectId: 'ssup-ca6a0',
    storageBucket: 'ssup-ca6a0.appspot.com',
    iosBundleId: 'com.example.ssup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9WTHm8sl3_-aLHU61Rk2SXVdKW_VCGU4',
    appId: '1:928586580604:ios:e1c58d44d46785480cbff9',
    messagingSenderId: '928586580604',
    projectId: 'ssup-ca6a0',
    storageBucket: 'ssup-ca6a0.appspot.com',
    iosBundleId: 'com.example.ssup.RunnerTests',
  );
}
